<?php

/**
 * The record will be automatically inserted, updated, or deleted from the
 * database as appropriate. For more details, see "hook_civicrm_managed" at:
 * https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_managed/
 */
return [
  0 => [
    'name' => 'CustomGroup_Contact_Creation_Info',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contact_Creation_Info',
        'title' => 'Contact Creation Info',
        'extends' => 'Contact',
        'extends_entity_column_id' => NULL,
        'extends_entity_column_value' => NULL,
        'style' => 'Inline',
        'collapse_display' => true,
        'help_pre' => '',
        'help_post' => '',
        'weight' => 6,
        'is_active' => true,
        'is_multiple' => false,
        'min_multiple' => NULL,
        'max_multiple' => NULL,
        'collapse_adv_display' => true,
        'created_date' => '2023-04-04 02:38:01',
        'is_reserved' => false,
        'is_public' => false,
        'icon' => '',
      ],
    ],
  ],
  1 => [
    'name' => 'CustomGroup_Contact_Creation_Info_CustomField_Created_By',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Contact_Creation_Info',
        'name' => 'Created_By',
        'label' => 'Created By',
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'default_value' => NULL,
        'is_required' => false,
        'is_searchable' => true,
        'is_search_range' => false,
        'help_pre' => NULL,
        'help_post' => NULL,
        'attributes' => NULL,
        'is_active' => true,
        'is_view' => true,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'created_by_14',
        'option_group_id' => NULL,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => false,
        'fk_entity' => NULL,
      ],
    ],
  ],
  2 => [
    'name' => 'CustomGroup_Contact_Creation_Info_CustomField_Created_On',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Contact_Creation_Info',
        'name' => 'Created_On',
        'label' => 'Created On',
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'default_value' => NULL,
        'is_required' => false,
        'is_searchable' => true,
        'is_search_range' => true,
        'help_pre' => NULL,
        'help_post' => NULL,
        'attributes' => NULL,
        'is_active' => true,
        'is_view' => true,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => 'yy-mm-dd',
        'time_format' => 2,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'created_on_15',
        'option_group_id' => NULL,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => false,
        'fk_entity' => NULL,
      ],
    ],
  ],
];